title: Edition Template
url: ''
baseurl: ''
google_analytics_key: null
show_full_navigation: true
logo: /siteicon.png
description: Product documentation template for Jekyll.
author:
  name: null
  email: null
  twitter: null
social:
  name: Edition Template
  links:
    - 'https://github.com/CloudCannon/edition-jekyll-template'
timezone: Etc/UTC
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
collections:
  docs:
    title: Documentation
    permalink: '/:path/'
    output: true
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: docs
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  - scope:
      path: ''
      type: posts
    values:
      _comments:
        type: Marks the impact of this release
types:
  - minor
  - major
